import { CommunityRO } from "./CommunityRO";
import { ConversationRO } from "./ConversationRO";
import { LastConversationRO } from "./LastConversationRO";
import { MemberRO } from "./MemberRO";
import { ReactionRO } from "./ReactionRO";

export interface ChatroomRO {
  id: string;
  communityId: string;
  title: string;
  state: number;
  member?: MemberRO | null;
  createdAt?: bigint | null;
  type?: number | null;
  chatroomImageUrl?: string | null;
  header?: string | null;
  cardCreationTime?: string | null;
  totalResponseCount: number;
  totalAllResponseCount: number;
  muteStatus?: boolean | null;
  followStatus?: boolean | null;
  hasBeenNamed?: boolean | null;
  date?: string | null;
  isTagged?: boolean | null;
  isPending?: boolean | null;
  deletedBy?: string | null;
  updatedAt?: bigint | null;
  lastConversation?: ConversationRO | null;
  lastConversationRO?: LastConversationRO | null;
  lastSeenConversationId?: string | null;
  lastSeenConversation?: ConversationRO | null;
  dateEpoch?: bigint | null;
  unseenCount: number;
  relationshipNeeded: boolean;
  draftConversation?: string | null;
  isSecret?: boolean | null;
  secretChatRoomParticipants: number[];
  secretChatRoomLeft?: boolean | null;
  conversations: ConversationRO[];
  topicId?: string | null;
  topic?: ConversationRO | null;
  autoFollowDone?: boolean | null;
  memberCanMessage?: boolean | null;
  isEdited?: boolean | null;
  reactions: ReactionRO[];
  unreadConversationsCount?: number | null;
  accessWithoutSubscription: boolean;
  externalSeen?: boolean | null;
  isConversationStored: boolean;
  isDraft?: boolean | null;
  lastConversationId?: string | null;
  communities?: CommunityRO[] | null;
}
